language: ruby
sudo: false
rvm: 2.2.0
script:
- git config --global user.email "travis@travis.ci"
- git config --global user.name "Travis CI"
- bundle exec rake deploy
env:
  global:
  - secure: ec1RY90XyAHWWyY2IyqwxpPTGG05UVRlwUhPXNWMHv/QXa1zAk5MQn5INSAKdbplz6L/AsnaR1RjrLGmZ59NM4NE6iXfgBd5KwMCCRTvD/rMf/qLNaYRGgacabQrMuwyihPrdgaC2Yeyejxh+EJqLquh+QX0z06NV2staHkRcHOrgUW0GvvpnL6SXQNZjuVngeWTNMHtwpn/HYAh254nVG3gtzeBFMuO4LTcxkBEYQvcumBrQLQjtPLivSAAFi5Npd52yZt6YZ3Gp48nAb5jSsxGDDIrS+OoCQCS8ACiD+9nG9c80QgGuE9r5w3dpL6d6+5xkn51fCih++/triZppmYb/fFI2wLdTpNQZMrwhDKqjXxCy3S3GZJUhWJVyJFFRueZ9Z6xJ12a6rfwpUgRPSFhwUocqx1e+Qro/VxO7n7Qw0gdVdu1CgBs6oUTefFY3fBU20gqMGdQ0JQrOY7fQDwJRSAgubIo6YWwCVWPykv3TF9RB9sWxRqkZVL/xj6gXRYWU53ApDKeDvtYzKdLvkjGcnl0uSSFBx0RJmIeBpPJl0YVcTX4TBMxP8iC+0VwXJLjJxUSjLzRG3GntU6Hndf1tfis48qgc3aG1eyArhbTA0svvcvJfpFOD9LozDG2P6zXFNPrSebLrT/JWqsdQhzJ0VfYncEvQv547iyaYW0=
before_install:
- openssl aes-256-cbc -K $encrypted_c0deb15f02e4_key -iv $encrypted_c0deb15f02e4_iv -in .deploy_key.enc -out .deploy_key -d
- chmod 600 .deploy_key

